#!/bin/bash

exec 2>testerror

echo "This is the start of the script"
echo "now redirecting output "

exec 1>testout

echo "This output should go to the testout file"
echo "This output should go to the testerror file" >&2
