#!/bin/bash

var1=10
while echo $var1
      [ $var1 -ge 0 ]
do 
    echo "This is inside th loop"
    var1=$[ $var1-1 ]
done

var2=100
until [ $var2 -eq 0 ]
do
    echo $var2
    var2=$[ $var2-25 ]
done
